In [9]:
import pandas as pd
from sqlalchemy import create_engine

In [10]:
csv_file = "winemag.csv"
winemag_df = pd.read_csv(csv_file)
winemag_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [11]:
csv_file2 = "white_wine.csv"
white_wine_df = pd.read_csv(csv_file2)
white_wine_df.head()

,FullName,Winery,WineName,Year,Region,RegionalVariety,VintageRating,VintageRatingCount,WineRating,WineRatingCount,VintagePrice,WinePrice,VintageRatingPriceRatio,WineRatingPriceRatio
0,Domaine Coche-Dury Meursault Les Rougeots 2001,Domaine Coche-Dury,Meursault Les Rougeots,2001,Burgundy,Côte de Beaune White,4.9,25,4.7,755,806.580,806.580,0.006075,0.005827
1,Joseph Drouhin Montrachet Grand Cru Marquis de...,Joseph Drouhin,Montrachet Grand Cru Marquis de Laguiche,2015,Burgundy,Côte de Beaune White,4.8,46,4.6,1191,680.000,680.000,0.007059,0.006765
2,Marcassin Marcassin Vineyard Chardonnay 2013,Marcassin,Marcassin Vineyard Chardonnay,2013,Californian,Chardonnay,4.8,28,4.6,884,448.000,448.000,0.010714,0.010268
3,M. Chapoutier Ermitage Le Méal Blanc 2006,M. Chapoutier,Ermitage Le Méal Blanc,2006,Northern Rhône,White,4.8,31,4.5,414,164.675,164.675,0.029148,0.027327
4,Domaine Coche-Dury Corton-Charlemagne Grand Cr...,Domaine Coche-Dury,Corton-Charlemagne Grand Cru,2007,Burgundy,Côte de Beaune White,4.8,35,4.7,454,3478.360,3478.360,0.001380,0.001351

In [14]:
csv_file3 = "majestic.csv"
majestic_df = pd.read_csv(csv_file3)
majestic_df.head()

,Unnamed: 0,num_ratings,positive_rating,price,wine_type,country,world,grape,region,rating_score
0,"""The Astronomer"" Chardonnay 2016 De Bortoli",61,54,6.99,white wine,australian,new world,NaN,NaN,0.885246
1,"'Angels' Share' Shiraz 2015 Two Hands, McLaren...",34,34,21.99,red wine,australian,new world,NaN,NaN,1.000000
2,A Lisa 2015 Bodega NoemÌa de Patagonia,16,15,28.00,fine wine,argentinian,new world,merlot,NaN,0.937500
3,A Sticky End Noble Sauvignon Blanc Half Bottle,13,12,17.99,white wine,new-zealand,new world,NaN,marlborough wine,0.923077
4,A.Gauvin Gevrey Chambertin 2015,3,3,40.00,fine wine,french,old world,NaN,burgundy,1.000000

In [15]:
csv_file4 = "QualityReds.csv"
quality_reds_df = pd.read_csv(csv_file4)
quality_reds_df.head()

,Unnamed: 0,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol,quality
0,1,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,2,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,3,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,4,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,5,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [19]:
csv_file5 = "QualityWhites.csv"
quality_whites_df = pd.read_csv(csv_file5)
quality_whites_df.head()

,Unnamed: 0,fixed.acidity,volatile.acidity,citric.acid,residual.sugar,chlorides,free.sulfur.dioxide,total.sulfur.dioxide,density,pH,sulphates,alcohol,quality
0,1,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,2,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,3,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,5,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [24]:
# get only the columns needed
new_winemag_df = winemag_df[['country', 'description', 'price', 'province', 'title', 'variety', 'winery']]
new_winemag_df
# renaming columns, making them consistent across the dbs
new_winemag_df = new_winemag_df.rename(columns={"country": "Country",
                                               "description": "Description",
                                               "price": "Price",
                                               "province": "Region",
                                               "title": "Full Name",
                                               "variety": "Variety",
                                               "winery": "Winery"})
new_winemag_df

,Country,Description,Price,Region,Full Name,Variety,Winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",NaN,Sicily & Sardinia,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",15.0,Douro,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",14.0,Oregon,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",13.0,Michigan,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",65.0,Oregon,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,28.0,Mosel,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,75.0,Oregon,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,30.0,Alsace,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",32.0,Alsace,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",21.0,Alsace,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [32]:
new_white_wine_df = white_wine_df[['FullName', 'Winery', 'WineName', 'Year', 'Region', 
                                   'RegionalVariety', 'VintageRating', 'WineRating', 'WinePrice']]
new_white_wine_df = new_white_wine_df.rename(columns={"FullName": "Full Name",
                                                      "Winery": "Winery",
                                                      "WineName": "Wine Name",
                                                      "Year": "Year",
                                                      "Region": "Region",
                                                      "RegionalVariety": "Variety",
                                                      "VintageRating": "Vintage Rating",
                                                      "WineRating": "Wine Rating",
                                                      "WinePrice": "Price"})
new_white_wine_df

,Full Name,Winery,Wine Name,Year,Region,Variety,Vintage Rating,Wine Rating,Price
0,Domaine Coche-Dury Meursault Les Rougeots 2001,Domaine Coche-Dury,Meursault Les Rougeots,2001,Burgundy,Côte de Beaune White,4.9,4.7,806.580
1,Joseph Drouhin Montrachet Grand Cru Marquis de...,Joseph Drouhin,Montrachet Grand Cru Marquis de Laguiche,2015,Burgundy,Côte de Beaune White,4.8,4.6,680.000
2,Marcassin Marcassin Vineyard Chardonnay 2013,Marcassin,Marcassin Vineyard Chardonnay,2013,Californian,Chardonnay,4.8,4.6,448.000
3,M. Chapoutier Ermitage Le Méal Blanc 2006,M. Chapoutier,Ermitage Le Méal Blanc,2006,Northern Rhône,White,4.8,4.5,164.675
4,Domaine Coche-Dury Corton-Charlemagne Grand Cr...,Domaine Coche-Dury,Corton-Charlemagne Grand Cru,2007,Burgundy,Côte de Beaune White,4.8,4.7,3478.360
...,...,...,...,...,...,...,...,...,...
4589,Domaine du Tunnel Saint-Péray Roussanne 2018,Domaine du Tunnel,Saint-Péray Roussanne,2018,Northern Rhône,Saint-Péray,4.0,4.0,23.530
4590,Brown Brothers Patricia Chardonnay 2010,Brown Brothers,Patricia Chardonnay,2010,Australian,Chardonnay,4.0,4.0,29.480
4591,Litmus Wines White Pinot 2015,Litmus Wines,White Pinot,2015,NaN,NaN,4.0,4.0,24.500
4592,Rollin Père et Fils Pernand-Vergelesses 'Les C...,Rollin Père et Fils,Pernand-Vergelesses 'Les Cloux',2017,Burgundy,Côte de Beaune White,4.0,4.1,20.160
4593,Suertes del Marqués Vidonia 2018,Suertes del Marqués,Vidonia,2018,NaN,NaN,4.0,3.9,21.340

In [33]:
new_majestic_df = majestic_df[['Unnamed: 0', 'price', 'wine_type', 'country', 'grape', 'region', 'rating_score']]
new_majestic_df = new_majestic_df.rename(columns={'Unnamed: 0': 'Full Name',
                                                 'price': 'Price',
                                                 'wine_type': 'Wine Type',
                                                 'country': 'Country',
                                                 'grape': 'Grape',
                                                  'region': 'Region',
                                                 'rating_score': 'Rating Score'})
new_majestic_df

,Full Name,Price,Wine Type,Country,Grape,Region,Rating Score
0,"""The Astronomer"" Chardonnay 2016 De Bortoli",6.99,white wine,australian,NaN,NaN,0.885246
1,"'Angels' Share' Shiraz 2015 Two Hands, McLaren...",21.99,red wine,australian,NaN,NaN,1.000000
2,A Lisa 2015 Bodega NoemÌa de Patagonia,28.00,fine wine,argentinian,merlot,NaN,0.937500
3,A Sticky End Noble Sauvignon Blanc Half Bottle,17.99,white wine,new-zealand,NaN,marlborough wine,0.923077
4,A.Gauvin Gevrey Chambertin 2015,40.00,fine wine,french,NaN,burgundy,1.000000
...,...,...,...,...,...,...,...
555,X de Larrivaux 2011,13.99,red wine,french,merlot,NaN,0.000000
556,Xanadu Exmoor Chardonnay,12.99,white wine,NaN,chardonnay,NaN,0.500000
557,Yalumba Y-Series Cabernet Sauvignon 2014 South...,10.99,red wine,NaN,NaN,NaN,0.800000
558,Z de Thienpont 2012,9.99,red wine,NaN,NaN,NaN,NaN
559,Zingo Malbec RosÈ 2017,9.99,rose wine,NaN,NaN,NaN,1.000000

In [34]:
new_quality_reds_df = quality_reds_df[['Unnamed: 0', 'fixed.acidity', 'volatile.acidity', 
                                       'citric.acid', 'residual.sugar', 'chlorides',
                                       'free.sulfur.dioxide', 'total.sulfur.dioxide',
                                       'density', 'pH', 'sulphates', 'alcohol', 'quality']]
new_quality_reds_df = new_quality_reds_df.rename(columns={'Unnamed: 0': 'ID',
                                                         'fixed.acidity': 'Fixed Acidity',
                                                         'volatile.acidity': 'Volatile Acidity',
                                                         'citric.acid': 'Citric Acid',
                                                        'residual.sugar': 'Residual Sugar',
                                                        'chlorides': 'Chlorides',
                                                         'free.sulfur.dioxide': 'Free Sulfur Dioxide',
                                                          'total.sulfur.dioxide': 'Total Sulfur Dioxide',
                                                          'density': 'Density',
                                                          'pH': 'pH',
                                                         'sulphates': 'Sulphates',
                                                          'alcohol': 'Alcohol',
                                                          'quality': 'Quality'})
new_quality_reds_df

,ID,Fixed Acidity,Volatile Acidity,Citric Acid,Residual Sugar,Chlorides,Free Sulfur Dioxide,Total Sulfur Dioxide,Density,pH,Sulphates,Alcohol,Quality
0,1,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,2,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,3,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,4,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,5,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,1595,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,1596,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,1597,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,1598,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,1599,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [35]:
new_quality_whites_df = quality_whites_df[['Unnamed: 0', 'fixed.acidity', 'volatile.acidity', 
                                       'citric.acid', 'residual.sugar', 'chlorides',
                                       'free.sulfur.dioxide', 'total.sulfur.dioxide',
                                       'density', 'pH', 'sulphates', 'alcohol', 'quality']]
new_quality_whites_df = new_quality_whites_df.rename(columns={'Unnamed: 0': 'ID',
                                                         'fixed.acidity': 'Fixed Acidity',
                                                         'volatile.acidity': 'Volatile Acidity',
                                                         'citric.acid': 'Citric Acid',
                                                        'residual.sugar': 'Residual Sugar',
                                                        'chlorides': 'Chlorides',
                                                         'free.sulfur.dioxide': 'Free Sulfur Dioxide',
                                                          'total.sulfur.dioxide': 'Total Sulfur Dioxide',
                                                          'density': 'Density',
                                                          'pH': 'pH',
                                                         'sulphates': 'Sulphates',
                                                          'alcohol': 'Alcohol',
                                                          'quality': 'Quality'})
new_quality_whites_df

,ID,Fixed Acidity,Volatile Acidity,Citric Acid,Residual Sugar,Chlorides,Free Sulfur Dioxide,Total Sulfur Dioxide,Density,pH,Sulphates,Alcohol,Quality
0,1,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,2,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,3,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,5,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,4894,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,4895,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,4896,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,4897,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,4898,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6